name: crime-intelligence-system

services:
  # --- RELATIONAL DATABASE ---
  db:
    image: postgres:16-alpine
    container_name: crime-intelligence-postgres
    environment:
      POSTGRES_DB: crimedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Exposed so your local Python Faker script can connect!
    volumes:
      - crime-intelligence-postgres-data:/var/lib/postgresql/data
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      # Notice: seed_data.sql has been removed from here!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crimedb"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- BIG DATA COMPONENTS ---
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: crime-hadoop-namenode
    environment:
      - CLUSTER_NAME=crime-cluster
    ports:
      - "9870:9870" # HDFS Web UI
      - "9000:9000" # HDFS internal communication
    volumes:
      - hadoop-namenode-data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: crime-hadoop-datanode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - hadoop-datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode

volumes:
  crime-intelligence-postgres-data:
  hadoop-namenode-data:
  hadoop-datanode-data: