# FROM node:20-slim

# WORKDIR /app

# # Look at the local files directly, without the folder prefix
# COPY package*.json ./
# RUN npm install

# # Copy everything else in the current folder
# COPY . .

# EXPOSE 3000

# # Start the dev server
# CMD ["npm", "run", "dev", "--", "--host"]